name: morphinet
channels:
  - pytorch
  - nvidia
  - pytorch3d
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.1.0
  - torchvision
  - pytorch-cuda=11.8
  - iopath
  - numpy
  - fvcore
  - pytorch3d
  - conda-forge::ninja
  - ipython
  - simpleitk
  - pip
  - pip:
      - monai==1.3.0
      - einops
      - wandb
      - plotly
      - scikit-image
      - matplotlib
      - nibabel
      - pandas
      - tqdm
      - pyvista
      - trimesh
      - nptyping
      - natsort
      - rtree
      - seaborn
      - ninja
      - pynrrd
      - SimpleITK
